# Generated by Django 5.0.14 on 2026-08-17 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JumpPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Tandem', 'Tandem'), ('AFF', 'AFF (Accelerated Freefall)'), ('Solo', 'Solo'), ('Group', 'Group')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('min_age', models.PositiveSmallIntegerField(default=18)),
                ('max_weight_kg', models.PositiveSmallIntegerField(default=100)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=20)),
                ('image_url', models.URLField(blank=True, help_text='Optional cover image URL')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('certification_level', models.CharField(choices=[('Tandem', 'Tandem Instructor'), ('AFF', 'AFF Instructor'), ('Coach', 'Skydive Coach'), ('Examiner', 'Examiner')], default='Tandem', max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('drop_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='dropzones.dropzone')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('capacity', models.PositiveSmallIntegerField(default=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('cancelled', 'Cancelled (Weather)')], default='open', max_length=12)),
                ('drop_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='dropzones.dropzone')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slots', to='dropzones.instructor')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('drop_zone', 'date', 'start_time', 'instructor')},
            },
        ),
    ]
