# Generated by Django 5.0.14 on 2026-08-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropzones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropzone',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional cover image URL for this drop zone'),
        ),
    ]
