# Generated by Django 5.0.14 on 2026-08-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropzones', '0002_dropzone_image_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('drop_zone', 'date', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
