# Generated by Django 5.0.14 on 2026-08-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Credit / Debit Card (simulated)'), ('paypal', 'PayPal (simulated)')], default='card', max_length=10),
        ),
    ]
