# Generated by Django 5.0.14 on 2026-08-18 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='group_size',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of jumpers in this booking (1 for solo, 2+ for group packages).'),
        ),
        migrations.CreateModel(
            name='BookingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('age', models.PositiveSmallIntegerField()),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_lead', models.BooleanField(default=False, help_text='True if this participant is the lead jumper / booker.')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='bookings.booking')),
            ],
            options={
                'ordering': ['is_lead', 'id'],
            },
        ),
    ]
